/**
 * Integration test for matchLists — hits the real API (OpenRouter by default).
 * Requires OPENROUTER_API_KEY to be set in .env. Weak-mode test is skipped when node-llama-cpp is not installed.
 *
 * Run with:
 *   node --test --require dotenv/config test/matchLists.live.test.ts
 *   (after building: npm run build && node --test test/matchLists.live.test.ts)
 */
import "dotenv/config";
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import type { MatchResult } from "../functions/list-matcher/matchLists.js";

// Note: dist/functions/index.js is generated by `npm run build`
import { matchLists } from "../dist/functions/index.js";

async function canUseLlamaCpp(): Promise<boolean> {
    try {
        await import("node-llama-cpp");
        return true;
    } catch {
        return false;
    }
}

describe("matchLists (live)", async () => {
    const hasLlamaCpp = await canUseLlamaCpp();
    const weakIt = hasLlamaCpp ? it : it.skip;
    it("matches fruits by name", async () => {
        const list1 = [
            { id: 1, name: "Apple" },
            { id: 2, name: "Banana" },
        ];
        const list2 = [
            { item: "Apple", category: "Fruit" },
            { item: "Banana", category: "Fruit" },
            { item: "Carrot", category: "Vegetable" },
        ];

        const result = await matchLists({
            list1,
            list2,
            guidance: "Match items by name only.",
        });

        assert.ok(Array.isArray(result.matches), "matches should be an array");
        assert.ok(Array.isArray(result.unmatched), "unmatched should be an array");
        assert.ok(result.matches.length === 2, `Expected 2 matches, got ${result.matches.length}`);

        const appleMatch = result.matches.find((m: MatchResult) => m.source.name === "Apple");
        assert.ok(appleMatch, "Should have matched Apple");
        assert.strictEqual(appleMatch!.target.item, "Apple");

        const bananaMatch = result.matches.find((m: MatchResult) => m.source.name === "Banana");
        assert.ok(bananaMatch, "Should have matched Banana");
        assert.strictEqual(bananaMatch!.target.item, "Banana");
    });

    it("leaves unmatched items in unmatched[]", async () => {
        const list1 = [
            { id: 10, label: "Mango" },
            { id: 11, label: "Dragonfruit" },
        ];
        const list2 = [{ name: "Mango" }];

        const result = await matchLists({
            list1,
            list2,
            guidance: "Match by label vs name. Items with no confident match go to unmatched.",
        });

        assert.ok(result.matches.length >= 1, "Mango should be matched");
        assert.ok(result.unmatched.length >= 1, "Dragonfruit should be unmatched");
    });

    weakIt("matches with mode weak", async () => {
        const list1 = [{ id: 1, name: "Orange" }];
        const list2 = [{ item: "Orange", category: "Fruit" }];
        const result = await matchLists({
            list1,
            list2,
            guidance: "Match by name only.",
            mode: "weak",
        });
        assert.ok(Array.isArray(result.matches));
        assert.ok(Array.isArray(result.unmatched));
        assert.ok(result.matches.length === 1);
        assert.strictEqual(result.matches[0].source.name, "Orange");
        assert.strictEqual(result.matches[0].target.item, "Orange");
    });

    it("skips already-mapped list1 items and merges with existingMatches (no doubles)", async () => {
        const apple = { id: 1, name: "Apple" };
        const banana = { id: 2, name: "Banana" };
        const list1 = [apple, banana];
        const list2 = [
            { item: "Apple", category: "Fruit" },
            { item: "Banana", category: "Fruit" },
        ];
        const existingMatches: MatchResult[] = [
            { source: apple, target: list2[0], reason: "exact" },
        ];
        const result = await matchLists({
            list1,
            list2,
            guidance: "Match by name only.",
            existingMatches,
        });
        assert.ok(result.matches.length >= 2, "should have existing + new match(es)");
        assert.strictEqual(result.matches[0].source.name, "Apple");
        assert.strictEqual(result.matches[0].target.item, "Apple");
        const bananaMatch = result.matches.find((m: MatchResult) => m.source.name === "Banana");
        assert.ok(bananaMatch, "Banana should be matched");
        assert.ok(Array.isArray(result.unmatched));
    });
});
