/**
 * Live integration test for match() — hits the real API (OpenRouter by default).
 * Requires OPENROUTER_API_KEY to be set in env/.env.
 *
 * Run with:
 *   npm run build && node --test --require dotenv/config test/match.live.test.ts
 */
import "dotenv/config";
import { describe, it } from "node:test";
import assert from "node:assert/strict";

// Note: dist/functions/index.js is generated by `npm run build`
import { match } from "../dist/functions/index.js";

function hasOpenRouterKey(): boolean {
  return typeof process.env.OPENROUTER_API_KEY === "string" && process.env.OPENROUTER_API_KEY.length > 0;
}

describe("match (live)", () => {
  const liveIt = hasOpenRouterKey() ? it : it.skip;

  liveIt("matches to the most relevant candidate IDs", async () => {
    const out = await match({
      query: "cve or equivalent vulnerability id",
      candidates: [
        { id: "root.refNorm", label: "Normalized reference field" },
        { id: "layers.nodes.cve", label: "CVE-like identifier on node records" },
        { id: "layers.records.pluginId", label: "Plugin identifier field" },
      ],
      guidance: "Prefer direct vulnerability identity fields over indirect signals.",
      maxResults: 2,
      allowNoMatch: false,
      mode: "normal",
    });

    assert.strictEqual(out.query.length > 0, true);
    assert.strictEqual(out.noMatch, false);
    assert.ok(Array.isArray(out.matches));
    assert.ok(out.matches.length >= 1 && out.matches.length <= 2);
    assert.ok(out.matches.every((m) => typeof m.id === "string"));
    assert.ok(out.matches.every((m) => typeof m.score === "number" && m.score >= 0 && m.score <= 1));
  });
});

